apiVersion: v1
kind: Service
metadata:
  name: skykube-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: skykube
  type: NodePort
