name: Build & Deploy to EKS

on:
    # push:
    #   branches:
    #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/skykube-repo:${GITHUB_SHA}
          echo "Building Docker image $IMAGE_URI"
          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI
          echo "image=$IMAGE_URI" >> $GITHUB_ENV

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name SkyKube-cluster

      - name: Deploy to EKS
        run: |
          # Update image in Kubernetes deployment YAML
          sed -i "s|image: .*|image: ${{ env.image }}|" k8s/deployment.yaml

          kubectl apply -f k8s/
          kubectl rollout status deployment skykube-deployment
